language: android
android:
  components:
    - build-tools-28.0.3
    - android-28

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew install

deploy:
  provider: bintray
  skip_cleanup: true
  file: bintray
  email: $BINTRAY_USER
  api_key: $BINTRAY_KEY
  on:
    branch: master
