name: CI

on:
  push: 
    branches-ignore: 
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pre-build
      run:  chmod +x ./gradlew
    - name: build
      run: ./gradlew clean assemble
    - name: version bump patch
      run: ./gradlew bumpPatchVersion