name: Release 

on: 
  push:
    tags:
      - 'v*'

jobs:         
  publish-gpr:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        env: 
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry-url: https://maven.pkg.github.com
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          java-version: 11
      - run: | 
              ./gradlew assembleRelease publish