name: Release 

on: 
  push:
    branches:
      - 'master'

jobs:         
  publish:

    runs-on: ubuntu-latest
    
    steps:
      - name: Publish and upload to bintray 
        uses: actions/checkout@master
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        env: 
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: |
              chmod +x gradlew
              ./gradlew install
              ./gradlew version
              ./gradlew :base-android-library:assembleRelease
              ./gradlew :base-android-library:bintrayUpload
        id: release_package
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          CUSTOM_TAG: ${{ steps.release_package.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false