name: Release 

on: 
  push:
    tags:
      - 'v*'

jobs:         
  publish:

    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Permission for gradlew
        run: chmod +x gradlew
      - name: Install
        run: ./gradlew install
      - name: Build
        run: ./gradlew :base-android-library:assembleRelease
      - name: Publish
        env: 
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew :base-android-library:bintrayUpload